### ISSUE TITLE
Why do we need freesurfer?

### ISSUE THREAD

**Issue by jdkent** [HBClab/RestingState#101]
### Summary
The containers are big and freesurfer is the largest contributor to that. What freesurfer commands do we run and how much from freesurfer do we need?

### Actual behavior
Containers take a long time to build and move

### Expected behavior
Containers should be "light-ish" weight when possible

### How to replicate the behavior
either build a container locally or pull from dockerhub.

### Script/Workflow details

Please put URL to code or code here (if not too long).

**Comment by tbweng** [comment]
@jdkent Good point. I _think_ freesurfer was a prerequisite because at some point your MBA skull stripping algorithm (which needs fs) was wrapped into these scripts. But based on that logic, MBWSS would have been a prereq as well...hmm :anguished:

A quick skim through the scripts suggests freesufer isn't needed. Will try a test run without freesufer loaded to verify.
