### ISSUE TITLE
permission errors for writing some niftis to seedmap directory

### ISSUE THREAD

**Issue by mwvoss** [HBClab/RestingState#81]
### Summary
When running new seeds with seedVoxelCorrelation.sh there are permission errors when trying to write some files to the seedmaps directory

### Actual behavior
example permission errors:
Restoring modules to user's neuro-packages
cp: cannot create regular file ‘/Shared/vosslabhpc/Projects/Bike_ATrain/Imaging/BIDS/derivatives/rsOut/sub-GEA290/ses-passivepost/seedCorrelation/compcor/rois/seeds_orig.txt’: Permission denied
cp: cannot create regular file ‘/Shared/vosslabhpc/Projects/Bike_ATrain/Imaging/BIDS/derivatives/rsOut/sub-GEA290/ses-passivepost/seedCorrelation/compcor/seedmaps/highres.nii.gz’: Permission denied
cp: cannot create regular file ‘/Shared/vosslabhpc/Projects/Bike_ATrain/Imaging/BIDS/derivatives/rsOut/sub-GEA290/ses-passivepost/seedCorrelation/compcor/seedmaps/highres2standard.nii.gz’: Permission denied
cp: cannot create regular file ‘/Shared/vosslabhpc/Projects/Bike_ATrain/Imaging/BIDS/derivatives/rsOut/sub-GEA290/ses-passivepost/seedCorrelation/compcor/seedmaps/standard.nii.gz’: Permission denied

### Expected behavior
No permission errors

### How to replicate the behavior
This may be from users running script other than tbweng?

### Script/Workflow details
This would happen running new seeds that generate a 3d seedmap

Please put URL to code or code here (if not too long).

**Comment by jdkent** [comment]
One step to debug this process could be cloning the repository on your local machine and run from there. I assume you are able to create files in those directories outside of the script?

**Comment by mwvoss** [comment]
I had trouble accessing the scripts on a local directory from the hpc. Tim had success cloning them to his user directory on hpc. I'd prefer my local drive if possible, any tips?

**Comment by jdkent** [comment]
To answer your direct question (if I understood it): I would not recommend trying to mount your mac's home directory (or a folder on your mac) to the hpc user directory because you are likely going to run into persnickety permissions issues.

From what you said it sounds like you were originally running the scripts on your local machine, and that was not working?

Do you want to use the computing power of the cluster? Permissions don't always map well from how we view the storage files (mounted via SMB) and how the hpc sees storage files (mounted via NFS), so I've ran into some strange permission errors, and it's just been easier to access scripts in the same environment that I call them.

If you want to mount your home directory (from your local machine) to the cluster, I'm sure it's possible, but it would require some set up on the mac side of things since the filesystem for mac is different than linux, and the changes you would have to make to your mac machine [are undesirable](https://help.ubuntu.com/community/hfsplus). Or perhaps [sshfs](https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh) could be used, but again I can't be sure about permission errors.

If you had cloned the repository on your local machine, and were calling the scripts from your local machine and getting permission errors, then my first check would be to see if I can write files to those directories normally.

**Comment by mwvoss** [comment]
it sounds like it's error prone to try to use scripts on my local mac drive while utilizing power of the cluster. i got permission errors when using the scripts in our UniversalSoftware directory on the server, and this seems to happen for files that another user (e.g., tbweng) makes so it may not be the scripts. in the past tbweng then changes permissions on files and scripts would run fine.

it is strange to me that some of the seedmaps wrote out fine but others didn't based on permission errors. 

one solution for now would be if @tbweng changes permissions within the script like in previous instances of errors like this. long-term not sure if this is avoidable or just something that will happen often on a cluster. @jdkent @tbweng if you have ideas for long-term fix without always writing in re-permissions of files that is ideal.

**Comment by jdkent** [comment]
My current framework is to treat github as my "local" machine. If I'm theoretically going to use the script more than once, then I will put it on github and clone it on the machine I need to use it on. This forces me to stay somewhat light and not build things with more dependencies than I can specify in the repository. I'm not always successful, but it's an ideal I work for. and if something becomes sufficiently complex, then thinking about a docker/singularity container becomes optimal. Long term, if this software is to be supported, then I see a transfer to a docker container/singularity container. Then at least we are dealing with permission issues with one object, instead however many scripts are in there.

**Comment by mwvoss** [comment]
Closing this, since we figured out the source of the permission errors with the help of an hpc admin.
